POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q1QGV4YW1wbGUuY29tIiwiZXhwIjoxNzYwNzE2NzMwLCJ1c2VySWQiOjN9.JHQj7v5uy3HBvMU7y6NJxoJWW4yY1yzcIKzpEAlzZVM

{
  "name": "Test event 5",
  "description": "A test event 2",
  "location": "A test location 2",
  "dateTime": "2025-01-02T15:30:00.000Z"
}