PUT http://localhost:8080/events/1
content-type: application/json

{
  "name": "updated test event",
  "description": "updated event",
  "location": "Updated test location",
  "dateTime": "2025-02-01T15:30:00Z"
}